import { SlideData, SlideType } from './types';

export const SLIDE_DATA: SlideData[] = [
  {
    id: 'slide-image-1',
    type: SlideType.Image,
    duration: 8000,
    imageUrl: 'https://picsum.photos/id/1018/1080/1920',
    title: 'Explore the Mountains',
    caption: 'Discover breathtaking views and serene landscapes.',
    qrCodeUrl: 'https://example.com/mountains',
    qrCodeText: 'Learn More',
  },
  {
    id: 'slide-video-1',
    type: SlideType.Video,
    duration: 15000,
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    title: 'A Moment of Fun',
    qrCodeUrl: 'https://example.com/video',
    qrCodeText: 'Watch Full Video',
  },
  {
    id: 'slide-poll-1',
    type: SlideType.Poll,
    duration: 12000,
    question: "What's your favorite local dish?",
    subtitle: "Help us decide the theme for next month's food festival!",
    imageUrl: 'https://picsum.photos/seed/dish/500/600',
    options: [
      { id: 'opt1', text: 'Callaloo Soup', votes: 120 },
      { id: 'opt2', text: 'Fried Jackfish', votes: 250 },
      { id: 'opt3', text: 'Breadfruit & Saltfish', votes: 180 },
    ],
    qrCodeUrl: 'https://example.com/poll',
    qrCodeText: 'Vote Now',
  },
  {
    id: 'slide-photocontest-1',
    type: SlideType.PhotoContest,
    duration: 10000,
    title: 'Vincy Sunset Contest',
    submissions: [
      { imageUrl: 'https://picsum.photos/id/1015/800/600', author: '@photolover1' },
      { imageUrl: 'https://picsum.photos/id/1016/800/600', author: '@sunsetchaser' },
      { imageUrl: 'https://picsum.photos/id/1019/800/600', author: '@islandvibes' },
    ],
    qrCodeUrl: 'https://example.com/contest',
    qrCodeText: 'Submit Your Photo',
  },
  {
    id: 'slide-trivia-1',
    type: SlideType.Trivia,
    duration: 10000,
    question: 'What is the capital of St. Vincent & the Grenadines?',
    options: ['Bridgetown', 'Kingstown', 'St. George\'s'],
    correctAnswerIndex: 1,
    funFact: 'Kingstown is known as the "City of Arches" for its numerous volcanic stone arches.',
    qrCodeUrl: 'https://example.com/trivia',
    qrCodeText: 'Play Trivia',
  },
  {
    id: 'slide-map-1',
    type: SlideType.Map,
    duration: 8000,
    mapUrl: 'https://picsum.photos/seed/map/1080/1920',
    title: 'Expo Floor Plan',
    highlightArea: 'Vendor Booth #24',
    qrCodeUrl: 'https://example.com/map',
    qrCodeText: 'View Full Map',
  },
  {
    id: 'slide-event-1',
    type: SlideType.EventHighlight,
    duration: 10000,
    title: 'Live Music Festival',
    date: 'Tonight @ 8:00 PM',
    imageUrl: 'https://picsum.photos/id/103/1080/1920',
    status: 'Now Live',
    qrCodeUrl: 'https://example.com/event',
    qrCodeText: 'More Info',
  },
  {
    id: 'slide-vendor-1',
    type: SlideType.VendorSpotlight,
    duration: 8000,
    vendorName: 'Vincy Fresh Juices',
    logoUrl: 'https://picsum.photos/seed/logo/200/200',
    bannerUrl: 'https://picsum.photos/id/1060/1080/1920',
    tagline: 'Taste the authentic flavor of the islands.',
    qrCodeUrl: 'https://example.com/vendor',
    qrCodeText: 'See Vendor Profile',
  },
  {
    id: 'slide-leaderboard-1',
    type: SlideType.Leaderboard,
    duration: 10000,
    title: 'Trivia Challenge Leaders',
    entries: [
      { rank: 1, name: 'IslandExpert', score: 2500, avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704d' },
      { rank: 2, name: 'QuizMaster', score: 2350, avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026705d' },
      { rank: 3, name: 'SVGPro', score: 2200, avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026706d' },
      { rank: 4, name: 'VincyVibe', score: 2100, avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026707d' },
      { rank: 5, name: 'SunSeeker', score: 1950, avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026708d' },
    ],
    qrCodeUrl: 'https://example.com/leaderboard',
    qrCodeText: 'Join the Challenge',
  },
  {
    id: 'slide-mapbox-1',
    type: SlideType.Mapbox,
    duration: 15000,
    title: 'Kingstown Harbour',
    description: 'Explore the vibrant capital city and its historic waterfront.',
    buttonText: 'View Details',
    longitude: -61.2253,
    latitude: 13.1565,
    zoom: 13,
    qrCodeUrl: 'https://example.com/kingstown',
    qrCodeText: 'Explore Kingstown',
  },
  {
    id: 'slide-social-1',
    type: SlideType.SocialFeed,
    duration: 12000,
    title: '#EverythingVincy',
    posts: [
      { id: 'p1', author: '@vincy_adventures', avatarUrl: 'https://i.pravatar.cc/150?u=post1', text: 'Having an amazing time at the festival! The food is incredible!', imageUrl: 'https://picsum.photos/id/237/400/300', likes: 142 },
      { id: 'p2', author: '@local_eats', avatarUrl: 'https://i.pravatar.cc/150?u=post2', text: 'Don\'t miss the craft market. So many talented artists here!', likes: 88 },
      { id: 'p3', author: '@beachlife', avatarUrl: 'https://i.pravatar.cc/150?u=post3', text: 'Perfect day in paradise!', imageUrl: 'https://picsum.photos/id/239/400/300', likes: 210 },
    ],
    qrCodeUrl: 'https://eveythingvincy.netlify.app/',
    qrCodeText: 'Open Feed',
  },
];